package com.cryptocarver.ui;

import java.util.LinkedHashMap;
import java.util.Map;

/** English source-text to bundle-key maps for the progressively localized module slices. */
public final class ModuleTextCatalog {
    private ModuleTextCatalog() { }

    private static Map<String, String> common() {
        Map<String, String> map = new LinkedHashMap<>();
        map.put("Apply Template:", "module.common.applyTemplate");
        map.put("Select a template...", "module.common.selectTemplate");
        map.put("Apply", "module.common.apply");
        map.put("Manage Template", "module.common.manageTemplate");
        map.put("Save Current as Personal Template...", "module.common.saveTemplate");
        map.put("Export Selected Template...", "module.common.exportTemplate");
        map.put("Import Template File...", "module.common.importTemplate");
        map.put("Delete Selected Personal Template", "module.common.deleteTemplate");
        map.put("Reset Defaults", "module.common.resetDefaults");
        map.put("Algorithm:", "module.common.algorithm");
        map.put("Algorithm", "module.common.algorithmPlain");
        map.put("Mode:", "module.common.mode");
        map.put("Padding:", "module.common.padding");
        map.put("Generate", "module.common.generate");
        map.put("Encrypt", "module.common.encrypt");
        map.put("Decrypt", "module.common.decrypt");
        map.put("Inspect", "module.common.inspect");
        map.put("Save to Lab", "module.common.saveToLab");
        map.put("Paste Key", "module.common.pasteKey");
        map.put("Load Key…", "module.common.loadKey");
        map.put("Use from Shelf", "module.common.useShelf");
        map.put("Input:", "module.common.input");
        map.put("Output:", "module.common.output");
        map.put("Cancel", "module.common.cancel");
        map.put("Reset", "module.common.reset");
        map.put("Ready", "module.common.ready");
        return map;
    }

    public static Map<String, String> cipher() {
        Map<String, String> map = common();
        map.put("Data Encryption & Decryption", "module.cipher.title");
        map.put("🔒 Symmetric Cipher (AES, DES, etc.)", "module.cipher.symmetric");
        map.put("Algorithm & Mode", "module.cipher.algorithmMode");
        map.put("Key Source", "module.cipher.keySource");
        map.put("Key Source *:", "module.cipher.keySourceRequired");
        map.put("IV / Nonce & AEAD parameters", "module.cipher.ivAead");
        map.put("AEAD Auth Tag:", "module.cipher.aeadTag");
        map.put("AAD (Optional):", "module.cipher.aad");
        map.put("File Cipher (Streaming)", "module.cipher.fileStreaming");
        map.put("OpenPGP (GPG compatible)", "module.cipher.openPgp");
        map.put("Asymmetric Cipher (RSA)", "module.cipher.asymmetric");
        map.put("Input data", "module.common.inputData");
        map.put("Output result", "module.common.outputResult");
        return map;
    }

    public static Map<String, String> authentication() {
        Map<String, String> map = common();
        map.put("1. Data to authenticate", "module.auth.dataTitle");
        map.put("Enter the message used to generate or verify the signature/MAC. Format is selected in the global 'Payload format' bar above.", "module.auth.dataHelp");
        map.put("🔏 Digital Signatures", "module.auth.signatures");
        map.put("Keys (PEM format):", "module.auth.keysPem");
        map.put("Private Key", "module.auth.privateKey");
        map.put("Public Key", "module.auth.publicKey");
        map.put("Paste Private Key from Clipboard", "module.auth.pastePrivate");
        map.put("Paste Public Key from Clipboard", "module.auth.pastePublic");
        map.put("Load Private Key…", "module.auth.loadPrivate");
        map.put("Load Public Key…", "module.auth.loadPublic");
        map.put("Ready to sign/verify", "module.auth.ready");
        map.put("Sign", "module.auth.sign");
        map.put("Verify Signature", "module.auth.verifySignature");
        map.put("🔐 Message Authentication Codes (MAC)", "module.auth.mac");
        map.put("2. MAC configuration", "module.auth.macConfig");
        map.put("Output length", "module.auth.outputLength");
        map.put("Key material", "module.auth.keyMaterial");
        map.put("Save key to Lab", "module.auth.saveKey");
        map.put("Paste MAC Key", "module.auth.pasteMac");
        map.put("Load MAC Key…", "module.auth.loadMac");
        map.put("Generate MAC", "module.auth.generateMac");
        map.put("Verify an existing MAC", "module.auth.verifyMac");
        map.put("Verify", "module.auth.verify");
        map.put("3. Result", "module.auth.result");
        return map;
    }

    public static Map<String, String> keys() {
        Map<String, String> map = common();
        map.put("🎛 Key Lab", "module.keys.keyLab");
        map.put("Search:", "module.common.search");
        map.put("Import Metadata", "module.keys.importMetadata");
        map.put("Export Metadata", "module.keys.exportMetadata");
        map.put("No keys in Lab. Generate or import one below!", "module.keys.empty");
        map.put("Add New Key", "module.keys.add");
        map.put("Name:", "module.common.name");
        map.put("Key Size:", "module.keys.keySize");
        map.put("Generate Key", "module.keys.generate");
        map.put("Import Key", "module.keys.import");
        map.put("Key Details", "module.keys.details");
        map.put("ID/Alias:", "module.keys.idAlias");
        map.put("Bits:", "module.keys.bits");
        map.put("KCV:", "module.keys.kcv");
        map.put("Fingerprint:", "module.keys.fingerprint");
        map.put("Origin:", "module.keys.origin");
        map.put("Created:", "module.keys.created");
        map.put("Modified:", "module.keys.modified");
        map.put("Status:", "module.keys.status");
        map.put("Key Value:", "module.keys.value");
        map.put("Reveal Value", "module.keys.reveal");
        map.put("Copy ID", "module.keys.copyId");
        map.put("Save Metadata", "module.keys.saveMetadata");
        map.put("Archive", "module.keys.archive");
        map.put("Delete Key", "module.keys.delete");
        map.put("🔑 Key Generation", "module.keys.generation");
        map.put("Type:", "module.keys.type");
        map.put("Generated Key Summary", "module.keys.summary");
        map.put("Copy Key", "module.keys.copyKey");
        map.put("Copy KCV", "module.keys.copyKcv");
        map.put("Copy Summary", "module.keys.copySummary");
        map.put("Validate & Calculate KCVs", "module.keys.validateKcv");
        map.put("🔎 Key Material Inspector", "module.keys.materialInspector");
        map.put("Inspect Material", "module.keys.inspectMaterial");
        map.put("🗄 KeyStore Inspector", "module.keys.keystoreInspector");
        map.put("Load", "module.common.load");
        map.put("Browse…", "module.common.browse");
        map.put("Save Profile", "module.common.saveProfile");
        map.put("Inspect KeyStore", "module.keys.inspectKeystore");
        map.put("🔐 PKCS#11 Token", "module.keys.pkcs11");
        map.put("Connect & Inspect", "module.keys.connectInspect");
        map.put("Disconnect", "module.keys.disconnect");
        map.put("Sign Data", "module.keys.signData");
        map.put("Verify Signature", "module.auth.verifySignature");
        map.put("🔗 Compare Public / Private Key", "module.keys.compare");
        map.put("Compare Pair", "module.keys.comparePair");
        map.put("🔀 Key Sharing (XOR Split/Combine)", "module.keys.sharing");
        map.put("Split Key", "module.keys.split");
        map.put("Combine Components", "module.keys.combine");
        map.put("🔐 Key Derivation (KDF)", "module.keys.kdf");
        map.put("Derive Key", "module.keys.derive");
        map.put("🔗 AES Key Wrap (RFC 3394 / RFC 5649)", "module.keys.keyWrap");
        map.put("Execute Key Wrap", "module.keys.executeWrap");
        map.put("🔒 TR-31 Key Blocks", "module.keys.tr31");
        return map;
    }

    public static Map<String, String> certificates() {
        Map<String, String> map = common();
        map.put("📜 Generate Certificate", "module.cert.generate");
        map.put("Organization:", "module.cert.organization");
        map.put("Org. Unit:", "module.cert.orgUnit");
        map.put("Country:", "module.cert.country");
        map.put("State:", "module.cert.state");
        map.put("Locality:", "module.cert.locality");
        map.put("Email:", "module.common.email");
        map.put("Validity (days):", "module.cert.validity");
        map.put("Key Type:", "module.cert.keyType");
        map.put("Sign Algorithm:", "module.cert.signAlgorithm");
        map.put("SAN DNS:", "module.cert.sanDns");
        map.put("SAN IP:", "module.cert.sanIp");
        map.put("Generate Certificate", "module.cert.generateCertificate");
        map.put("Generate CSR", "module.cert.generateCsr");
        map.put("🏛 Issue Certificate from CSR (Laboratory CA)", "module.cert.issue");
        map.put("Issue Laboratory Certificate", "module.cert.issueButton");
        map.put("🔍 Parse Certificate", "module.cert.parse");
        map.put("Paste PEM Certificate:", "module.cert.pastePem");
        map.put("Certificate format:", "module.cert.format");
        map.put("Parse Certificate", "module.cert.parseButton");
        map.put("⚖ Compare Certificates", "module.cert.compare");
        map.put("Compare Certificates", "module.cert.compareButton");
        map.put("🛡 Validate Certificate", "module.cert.validate");
        map.put("Validate Certificate", "module.cert.validateButton");
        map.put("Validation Report", "module.cert.validationReport");
        map.put("🔗 Validate Chain", "module.cert.validateChain");
        map.put("Validate Chain", "module.cert.validateChainButton");
        map.put("🚫 CRL Management", "module.cert.crl");
        map.put("Generate Empty CRL", "module.cert.generateCrl");
        map.put("Revoke & Update CRL", "module.cert.updateCrl");
        map.put("📄 PAdES PDF Signatures", "module.cert.pades");
        map.put("📦 ASiC-S Containers", "module.cert.asic");
        map.put("📦 CMS Operations", "module.cert.cms");
        map.put("Load Token Keys", "module.cert.loadTokenKeys");
        map.put("Output / Result:", "module.cert.outputResult");
        return map;
    }

    public static Map<String, String> generic() {
        Map<String, String> map = common();
        map.put("🛠 Key & Certificate Format Workbench", "module.generic.workbench");
        map.put("🔐 Hashing", "module.generic.hashing");
        map.put("Calculate Hash", "module.generic.calculateHash");
        map.put("📦 Batch Runner", "module.generic.batch");
        map.put("Run Batch", "module.generic.runBatch");
        map.put("Dry Run", "module.generic.dryRun");
        map.put("Load CSV / JSON Lines…", "module.generic.loadBatch");
        map.put("Export Results…", "module.generic.exportResults");
        map.put("🔄 File Conversion", "module.generic.fileConversion");
        map.put("Convert File", "module.generic.convertFile");
        map.put("Compare Files (streaming)", "module.generic.compareFiles");
        map.put("Preview First 4 KiB", "module.generic.preview");
        map.put("🔤 Manual Conversion", "module.generic.manualConversion");
        map.put("Convert Data", "module.generic.convertData");
        map.put("Compress", "module.generic.compress");
        map.put("Decompress", "module.generic.decompress");
        map.put("Check Digit:", "module.generic.checkDigit");
        map.put("Validation Result:", "module.generic.validationResult");
        map.put("Runs safe, deterministic transformations. Input must contain an input column; no secret keys are accepted.", "module.batch.help");
        map.put("Key (Hex):", "module.batch.keyHex");
        map.put("IV/Nonce:", "module.batch.ivNonce");
        map.put("AAD:", "module.batch.aad");
        map.put("Hex (Req. for CBC)", "module.batch.ivPrompt");
        map.put("Hex (Optional for AEAD)", "module.batch.aadPrompt");
        map.put("32 bytes (only in memory)", "module.batch.keyPrompt");
        map.put("Charset:", "module.batch.charset");
        map.put("Stop on error", "module.batch.stopOnError");
        map.put("Compact records", "module.batch.compact");
        map.put("Load CSV / JSON Lines…", "module.generic.loadBatch");
        map.put("Export Results…", "module.generic.exportResults");
        return map;
    }

    public static Map<String, String> processDesigner() {
        Map<String, String> map = common();
        map.put("🧩 Process Designer (MVP)", "module.process.title");
        map.put("Compose safe workflows by dragging blocks and connecting them. Process files store configuration, never secret keys.", "module.process.help");
        map.put("Process:", "module.process.process");
        map.put("Untitled process", "module.process.untitled");
        map.put("Run", "module.process.run");
        map.put("Dry Run", "module.process.dryRun");
        map.put("Cancel", "module.common.cancel");
        map.put("Expand results", "module.process.expandResults");
        map.put("Reverse connection", "module.process.reverseConnection");
        map.put("Hide inspector", "module.process.hideInspector");
        map.put("Show inspector", "module.process.showInspector");
        map.put("Presets", "module.process.presets");
        map.put("Save…", "module.common.save");
        map.put("Open…", "module.common.open");
        map.put("Inputs", "module.process.inputs");
        map.put("Conversions", "module.process.conversions");
        map.put("Crypto", "module.process.crypto");
        map.put("Outputs", "module.process.outputs");
        map.put("Console input", "module.process.consoleInput");
        map.put("File input", "module.process.fileInput");
        map.put("Console output", "module.process.consoleOutput");
        map.put("File output", "module.process.fileOutput");
        map.put("Node name", "module.process.nodeName");
        map.put("Describe this step", "module.process.nodePrompt");
        map.put("Text / console value", "module.process.textValue");
        map.put("File path", "module.process.filePath");
        map.put("Browse", "module.common.browse");
        map.put("Mode", "module.common.mode");
        map.put("Charset", "module.process.charset");
        map.put("Hash Algorithm", "module.process.hashAlgorithm");
        map.put("Algorithm/Mode", "module.process.algorithmMode");
        map.put("Username", "module.process.username");
        map.put("Password", "module.process.password");
        map.put("Key Format", "module.process.keyFormat");
        map.put("Manual Key (Secret)", "module.process.manualKey");
        map.put("Nonce / IV", "module.process.nonceIv");
        map.put("Auto-generate", "module.process.autoGenerate");
        map.put("Connected inputs", "module.process.connectedInputs");
        map.put("Cipher output", "module.process.cipherOutput");
        map.put("Key size (bits)", "module.process.keySize");
        map.put("PBKDF2 iterations", "module.process.pbkdf2Iterations");
        map.put("Generated key algorithm", "module.process.generatedKeyAlgorithm");
        map.put("Length (bytes)", "module.process.lengthBytes");
        map.put("Keystore path", "module.process.keystorePath");
        map.put("Keystore Type", "module.process.keystoreType");
        map.put("Alias", "module.process.alias");
        map.put("Keystore Password", "module.process.keystorePassword");
        map.put("Key Password", "module.process.keyPassword");
        map.put("Public Material Path", "module.process.publicMaterialPath");
        map.put("Material Type", "module.process.materialType");
        map.put("Secrets are not stored in process files.", "module.process.secretsNotStored");
        map.put("Save block settings", "module.process.saveBlock");
        map.put("Select 2 blocks to connect", "module.process.selectTwo");
        map.put("Connect to...", "module.process.connectTo");
        map.put("Reverse selected connection", "module.process.reverseSelected");
        map.put("Delete selected", "module.process.deleteSelected");
        map.put("Clear canvas", "module.process.clearCanvas");
        map.put("Execution status", "module.process.executionStatus");
        map.put("Step", "module.process.step");
        map.put("Operation", "module.process.operation");
        map.put("Input", "module.common.input");
        map.put("Output", "module.common.output");
        map.put("Status", "module.process.status");
        map.put("Duration", "module.process.duration");
        map.put("Execution results", "module.process.executionResults");
        map.put("Execution results and validation messages appear here.", "module.process.executionPrompt");
        return map;
    }

    public static Map<String, String> history() {
        Map<String, String> map = new LinkedHashMap<>();
        map.put("Recent Operations", "module.history.title");
        map.put("Values:", "module.history.values");
        map.put("⚠ Unsafe lab: sensitive values are visible", "module.history.unsafe");
        map.put("Filter:", "module.history.filter");
        map.put("Operation, date or property", "module.history.filterPrompt");
        map.put("Module:", "module.history.module");
        map.put("All modules", "module.history.allModules");
        map.put("Clear filters", "module.history.clearFilters");
        map.put("Compare 2", "module.history.compareTwo");
        map.put("Import Recipe", "module.history.importRecipe");
        map.put("Clear History", "module.history.clear");
        map.put("The latest operation is selected automatically. Select a different row to export it.", "module.history.help");
        map.put("Open Selected Value", "module.history.openValue");
        map.put("Add Output to Shelf", "module.history.addShelf");
        map.put("Copy Selected Value", "module.history.copyValue");
        map.put("Export JSON Record", "module.history.exportJson");
        map.put("Export Visible JSON", "module.history.exportVisibleJson");
        map.put("Export Markdown Report", "module.history.exportReport");
        map.put("Copy Markdown Report", "module.history.copyReport");
        map.put("Export JSON Recipe", "module.history.exportRecipe");
        map.put("Time", "module.history.time");
        map.put("Operation", "module.history.operation");
        map.put("Action", "module.history.action");
        map.put("Operation Details", "module.history.details");
        map.put("Property", "module.history.property");
        map.put("Value", "module.history.value");
        map.put("Class", "module.history.class");
        return map;
    }

    public static Map<String, String> clipboardShelf() {
        Map<String, String> map = new LinkedHashMap<>();
        map.put("Clipboard Shelf / Laboratory Notebook", "module.shelf.title");
        map.put("Stores, tags, annotates and compares results generated or copied during this session.", "module.shelf.help");
        map.put("Search label, operation, tag, note...", "module.shelf.searchPrompt");
        map.put("All (Pinned & Unpinned)", "module.shelf.allPinned");
        map.put("All Operations", "module.shelf.allOperations");
        map.put("Any Format", "module.shelf.anyFormat");
        map.put("Any Classification", "module.shelf.anyClassification");
        map.put("Open Copy Window", "module.shelf.openCopy");
        map.put("Clear Shelf", "module.shelf.clear");
        map.put("No saved laboratory results yet", "module.shelf.empty");
        map.put("Time", "module.shelf.time");
        map.put("Label", "module.shelf.label");
        map.put("Source", "module.shelf.source");
        map.put("Algorithm", "module.shelf.algorithm");
        map.put("Format", "module.shelf.format");
        map.put("Class", "module.shelf.class");
        map.put("Tags", "module.shelf.tags");
        map.put("Preview", "module.shelf.preview");
        map.put("Entry Details", "module.shelf.details");
        map.put("⚠️ Contains sensitive data", "module.shelf.sensitive");
        map.put("Pin", "module.shelf.pin");
        map.put("Edit Note & Tags", "module.shelf.editNoteTags");
        map.put("Compare...", "module.shelf.compare");
        map.put("Use in...", "module.shelf.useIn");
        map.put("Copy", "module.shelf.copy");
        map.put("Open Expanded", "module.shelf.openExpanded");
        map.put("Rename", "module.shelf.rename");
        map.put("Delete", "module.shelf.delete");
        return map;
    }

    public static Map<String, String> compareResults() {
        Map<String, String> map = new LinkedHashMap<>();
        map.put("Compare Laboratory Results", "module.compare.title");
        map.put("Zero-crypto side-by-side comparison of stored result snapshots.", "module.compare.help");
        map.put("Property", "module.compare.property");
        map.put("Item 1", "module.compare.item1");
        map.put("Item 2", "module.compare.item2");
        map.put("Label", "module.compare.label");
        map.put("Source Operation", "module.compare.source");
        map.put("Algorithm", "module.compare.algorithm");
        map.put("Timestamp", "module.compare.timestamp");
        map.put("Format / Size", "module.compare.formatSize");
        map.put("Classification", "module.compare.classification");
        map.put("SHA-256 Hash", "module.compare.sha256");
        map.put("Diff Details", "module.compare.diffDetails");
        map.put("Export Comparison Report...", "module.compare.export");
        map.put("Close", "module.common.close");
        return map;
    }

    public static Map<String, String> pqc() {
        Map<String, String> map = common();
        map.put("🔑 PQC Key Generation", "module.pqc.keyGeneration");
        map.put("Algorithm (NIST Standards):", "module.pqc.algorithmNist");
        map.put("Generate Key Pair", "module.pqc.generatePair");
        map.put("Import PEM Keys...", "module.pqc.importPem");
        map.put("Export Public...", "module.pqc.exportPublic");
        map.put("Export Private...", "module.pqc.exportPrivate");
        map.put("Use from Shelf", "module.common.useShelf");
        map.put("Public Key", "module.pqc.publicKey");
        map.put("Private Key", "module.pqc.privateKey");
        map.put("Key Details", "module.pqc.keyDetails");
        map.put("🔏 PQC Sign / Verify", "module.pqc.signVerify");
        map.put("Data to Sign (UTF-8):", "module.pqc.dataToSign");
        map.put("Sign Data", "module.pqc.signData");
        map.put("Signature (Hex):", "module.pqc.signatureHex");
        map.put("Verify Signature (Paste Hex):", "module.pqc.verifySignatureHex");
        map.put("Paste Signature", "module.pqc.pasteSignature");
        map.put("Verify Signature", "module.pqc.verifySignature");
        map.put("🎓 KEM Educational Demo (Alice & Bob)", "module.pqc.kemDemo");
        map.put("This demo illustrates the Key Encapsulation Mechanism (KEM). It is not a full communication protocol.", "module.pqc.kemHelp");
        map.put("1. Alice generates a key pair (uses the ML-KEM key generated above).", "module.pqc.aliceStep");
        map.put("KEM algorithm:", "module.pqc.kemAlgorithm");
        map.put("2. Bob uses Alice's public key to encapsulate a shared secret.", "module.pqc.bobStep");
        map.put("Bob: Encapsulate Shared Secret", "module.pqc.encapsulate");
        map.put("Encapsulation Ciphertext sent to Alice (Hex):", "module.pqc.ciphertextHex");
        map.put("Bob's Shared Secret (Hex):", "module.pqc.bobSecretHex");
        map.put("3. Alice decapsulates the ciphertext using her private key.", "module.pqc.aliceDecapsulateStep");
        map.put("Alice: Decapsulate Ciphertext", "module.pqc.decapsulate");
        map.put("Alice's Shared Secret (Hex):", "module.pqc.aliceSecretHex");
        map.put("Generate an ML-KEM key pair to begin.", "module.pqc.kemEmpty");
        map.put("⏱️ Benchmark & Performance", "module.pqc.benchmark");
        map.put("Run Benchmark", "module.pqc.runBenchmark");
        return map;
    }

    public static Map<String, String> xmlSecurity() {
        Map<String, String> map = common();
        map.put("📝 Sign XML (XAdES)", "module.xml.signTitle");
        map.put("XML File to Sign:", "module.xml.inputFile");
        map.put("Signature Source:", "module.xml.signatureSource");
        map.put("Local KeyStore / PEM", "module.xml.localSource");
        map.put("Connected PKCS#11 Token", "module.xml.tokenSource");
        map.put("PKCS#12 / JKS / PEM KeyStore:", "module.xml.keyStore");
        map.put("KeyStore Password:", "module.xml.keyStorePassword");
        map.put("Key Alias (Select Key):", "module.xml.keyAlias");
        map.put("Load Keys", "module.xml.loadKeys");
        map.put("Signature Level:", "module.xml.signatureLevel");
        map.put("Signature Packaging:", "module.xml.signaturePackaging");
        map.put("TSA (required for T/LT/LTA):", "module.xml.tsa");
        map.put("Select a preset or enter your corporate TSA URL", "module.xml.tsaPrompt");
        map.put("Save TSA", "module.xml.saveTsa");
        map.put("Test TSA", "module.xml.testTsa");
        map.put("TSA Auth:", "module.xml.tsaAuth");
        map.put("TSA Profile:", "module.xml.tsaProfile");
        map.put("Saved TSA profile", "module.xml.savedTsaProfile");
        map.put("Save New Profile:", "module.xml.saveNewProfile");
        map.put("Profile name", "module.xml.profileName");
        map.put("Save Profile", "module.xml.saveProfile");
        map.put("Sign XML", "module.xml.sign");
        map.put("Signed XML Output:", "module.xml.signedOutput");
        map.put("Save Signed XML...", "module.xml.saveSigned");
        map.put("🔬 Inspect Signed XML", "module.xml.inspectTitle");
        map.put("Signed XML to inspect (local structural analysis, no validation):", "module.xml.inspectHelp");
        map.put("Open XML...", "module.xml.openXml");
        map.put("Inspect Signed XML", "module.xml.inspect");
        map.put("Signature structure report:", "module.xml.structureReport");
        map.put("⏱ RFC 3161 Timestamp", "module.xml.timestampTitle");
        map.put("File to timestamp:", "module.xml.timestampFile");
        map.put("Imprint hash:", "module.xml.imprintHash");
        map.put("TSA URL:", "module.xml.tsaUrl");
        map.put("Request Timestamp", "module.xml.requestTimestamp");
        map.put("Save Token...", "module.xml.saveToken");
        map.put("Saved token to inspect (opt):", "module.xml.savedToken");
        map.put("TrustStore (optional):", "module.xml.trustStoreOptional");
        map.put("TrustStore Path:", "module.xml.trustStorePath");
        map.put("Inspect Token", "module.xml.inspectToken");
        map.put("Validate Token", "module.xml.validateToken");
        map.put("RFC 3161 token report:", "module.xml.timestampReport");
        map.put("🔍 Verify XML (XAdES)", "module.xml.verifyTitle");
        map.put("Paste Signed XML Content:", "module.xml.pasteSigned");
        map.put("TrustStore Profile (opt):", "module.xml.trustStoreProfile");
        map.put("Saved KeyStore profile", "module.xml.savedKeyStore");
        map.put("TrustStore Password:", "module.xml.trustStorePassword");
        map.put("Verify XML", "module.xml.verify");
        map.put("Verification Report:", "module.xml.verificationReport");
        return map;
    }

    public static Map<String, String> wssSecurity() {
        Map<String, String> map = common();
        map.put("🔐 Sign SOAP (WSS)", "module.wss.signTitle");
        map.put("SOAP 1.1/1.2 · X.509 BinarySecurityToken + SecurityTokenReference", "module.wss.signHelp");
        map.put("SOAP XML to Sign:", "module.wss.soapToSign");
        map.put("Paste SOAP XML here...", "module.wss.soapPrompt");
        map.put("Load from File...", "module.wss.loadFile");
        map.put("Signature Algorithm:", "module.wss.signatureAlgorithm");
        map.put("Timestamp Options:", "module.wss.timestampOptions");
        map.put("Add wsu:Timestamp", "module.wss.addTimestamp");
        map.put("Validity (min):", "module.wss.validity");
        map.put("Protect Timestamp", "module.wss.protectTimestamp");
        map.put("KeyStore (JKS/PKCS12):", "module.wss.keyStore");
        map.put("KeyStore Password:", "module.wss.keyStorePassword");
        map.put("Key Alias:", "module.wss.keyAlias");
        map.put("Load Keys", "module.wss.loadKeys");
        map.put("Private Key Password:", "module.wss.privateKeyPassword");
        map.put("Leave blank if same as KeyStore", "module.wss.privateKeyPrompt");
        map.put("Sign SOAP Body", "module.wss.signBody");
        map.put("Signed SOAP Output:", "module.wss.signedOutput");
        map.put("Save Signed XML...", "module.wss.saveSigned");
        map.put("✅ Verify SOAP (WSS)", "module.wss.verifyTitle");
        map.put("The SOAP version and embedded X.509 token are detected automatically.", "module.wss.verifyHelp");
        map.put("Paste Signed SOAP XML Content:", "module.wss.pasteSigned");
        map.put("Trusted Certificate:", "module.wss.trustedCertificate");
        map.put("Verify SOAP Signature", "module.wss.verifySignature");
        map.put("Verification Report:", "module.wss.verificationReport");
        map.put("👤 Add UsernameToken (WSS)", "module.wss.usernameTitle");
        map.put("Adds credentials to wsse:Security. This is authentication data, not a cryptographic signature.", "module.wss.usernameHelp");
        map.put("SOAP XML:", "module.wss.soapXml");
        map.put("Username:", "module.wss.username");
        map.put("Password:", "module.wss.password");
        map.put("Password format:", "module.wss.passwordFormat");
        map.put("Add UsernameToken", "module.wss.addUsername");
        map.put("SOAP Output:", "module.wss.soapOutput");
        map.put("Save SOAP XML...", "module.wss.saveSoap");
        map.put("🔎 Verify UsernameToken (WSS)", "module.wss.verifyUsernameTitle");
        map.put("Checks username/password, nonce encoding and Created freshness. It does not validate a SOAP signature or TLS.", "module.wss.verifyUsernameHelp");
        map.put("SOAP XML with UsernameToken:", "module.wss.soapWithUsername");
        map.put("Expected username:", "module.wss.expectedUsername");
        map.put("Expected password:", "module.wss.expectedPassword");
        map.put("Max token age (sec):", "module.wss.maxAge");
        map.put("Verify UsernameToken", "module.wss.verifyUsername");
        map.put("🔒 Encrypt SOAP Body (WSS)", "module.wss.encryptTitle");
        map.put("Encrypts the SOAP Body content with a fresh AES key and transports that key with the recipient RSA certificate.", "module.wss.encryptHelp");
        map.put("Recipient Certificate:", "module.wss.recipientCertificate");
        map.put("Data encryption:", "module.wss.dataEncryption");
        map.put("Key transport:", "module.wss.keyTransport");
        map.put("Encrypt SOAP Body", "module.wss.encryptBody");
        map.put("Encrypted SOAP Output:", "module.wss.encryptedOutput");
        map.put("Encryption Report:", "module.wss.encryptionReport");
        map.put("Save Encrypted XML...", "module.wss.saveEncrypted");
        map.put("🔓 Decrypt SOAP Body (WSS)", "module.wss.decryptTitle");
        map.put("Decrypts EncryptedKey and EncryptedData using an RSA private key from PKCS#12/JKS.", "module.wss.decryptHelp");
        map.put("Encrypted SOAP XML:", "module.wss.encryptedXml");
        map.put("Decryption KeyStore:", "module.wss.decryptionKeyStore");
        map.put("KeyStore password:", "module.wss.keyStorePasswordLower");
        map.put("Private key password:", "module.wss.privateKeyPasswordLower");
        map.put("If different", "module.wss.ifDifferent");
        map.put("Decrypt SOAP Body", "module.wss.decryptBody");
        map.put("Decrypted SOAP Output:", "module.wss.decryptedOutput");
        map.put("Decryption Report:", "module.wss.decryptionReport");
        map.put("Save Decrypted XML...", "module.wss.saveDecrypted");
        return map;
    }

    public static Map<String, String> jose() {
        Map<String, String> map = common();
        map.put("JSON Web Token (JWT)", "module.jose.jwtTitle");
        map.put("Generate JWT", "module.jose.generateJwt");
        map.put("Template:", "module.jose.template");
        map.put("Select Template...", "module.jose.selectTemplate");
        map.put("Serialization:", "module.jose.serialization");
        map.put("Unencoded Payload (b64=false)", "module.jose.unencodedPayload");
        map.put("WARNING: May cause interoperability issues with standard parsers", "module.jose.unencodedWarning");
        map.put("Signing Key 1:", "module.jose.signingKey1");
        map.put("Import from File...", "module.jose.importFile");
        map.put("Signer 2 (Only for General JSON)", "module.jose.signer2");
        map.put("Algorithm 2:", "module.jose.algorithm2");
        map.put("Signing Key 2:", "module.jose.signingKey2");
        map.put("Claims Builder (Optional)", "module.jose.claimsBuilder");
        map.put("Issuer (iss):", "module.jose.issuer");
        map.put("Subject (sub):", "module.jose.subject");
        map.put("Audience (aud):", "module.jose.audience");
        map.put("Valid for:", "module.jose.validFor");
        map.put("hours", "module.jose.hours");
        map.put("Apply to Payload", "module.jose.applyPayload");
        map.put("Payload (JSON):", "module.jose.payloadJson");
        map.put("Generate Signed JWT", "module.jose.generateSigned");
        map.put("Validate & Decode JWT", "module.jose.validateJwt");
        map.put("JWT Token:", "module.jose.jwtToken");
        map.put("Verification Key:", "module.jose.verificationKey");
        map.put("Advanced Validation Settings", "module.jose.advancedValidation");
        map.put("Expected Issuer (iss):", "module.jose.expectedIssuer");
        map.put("Expected Audience (aud):", "module.jose.expectedAudience");
        map.put("Clock Skew (sec):", "module.jose.clockSkew");
        map.put("Check Expiration (exp/nbf/iat)", "module.jose.checkExpiration");
        map.put("Strict OIDC Profile", "module.jose.strictOidc");
        map.put("Verify & Decode", "module.jose.verifyDecode");
        map.put("Decoded Header:", "module.jose.decodedHeader");
        map.put("Decoded Payload:", "module.jose.decodedPayload");
        map.put("JWS Detached (External Payload)", "module.jose.detachedTitle");
        map.put("External Payload:", "module.jose.externalPayload");
        map.put("Generate Detached JWS", "module.jose.generateDetached");
        map.put("Verify Detached JWS", "module.jose.verifyDetached");
        map.put("Output / Result:", "module.jose.outputResult");
        map.put("JSON Web Keys (JWK)", "module.jose.jwkTitle");
        map.put("JWK Tools", "module.jose.jwkTools");
        map.put("Key Type:", "module.jose.keyType");
        map.put("Key ID (kid):", "module.jose.keyId");
        map.put("Calc Thumbprint", "module.jose.calcThumbprint");
        map.put("JWK Set (JWKS)", "module.jose.jwksTitle");
        map.put("New JWKS", "module.jose.newJwks");
        map.put("Load JWKS...", "module.jose.loadJwks");
        map.put("Key Rotation & Operations", "module.jose.rotation");
        map.put("Simulate Key Rotation:", "module.jose.simulateRotation");
        map.put("Add New Key to Set", "module.jose.addKey");
        map.put("Public Export:", "module.jose.publicExport");
        map.put("Show Public JWKS Only", "module.jose.publicOnly");
        map.put("JSON Web Encryption (JWE)", "module.jose.jweTitle");
        map.put("Encrypt", "module.jose.encrypt");
        map.put("Key Management:", "module.jose.keyManagement");
        map.put("Content:", "module.jose.content");
        map.put("Compress (DEF)", "module.jose.compress");
        map.put("Recipient Public Key:", "module.jose.recipientKey");
        map.put("Payload (Any String):", "module.jose.payloadAny");
        map.put("Encrypt & Generate JWE", "module.jose.generateJwe");
        map.put("Output (JWE):", "module.jose.jweOutput");
        map.put("Decrypt", "module.jose.decrypt");
        map.put("JWE Token:", "module.jose.jweToken");
        map.put("Private Key (PEM):", "module.jose.privatePem");
        map.put("Decrypt JWE", "module.jose.decryptJwe");
        map.put("Visual Breakdown (Layer 6)", "module.jose.visualBreakdownLayer");
        map.put("Protected Header:", "module.jose.protectedHeader");
        map.put("Encrypted Key:", "module.jose.encryptedKey");
        map.put("Decrypted CEK (Hex):", "module.jose.decryptedCek");
        map.put("Initialization Vector (IV):", "module.jose.iv");
        map.put("Ciphertext (Truncated):", "module.jose.ciphertext");
        map.put("Authentication Tag:", "module.jose.authTag");
        map.put("Nested (Sign + Encrypt)", "module.jose.nested");
        map.put("1. Inner Token (Signed):", "module.jose.innerToken");
        map.put("2. Outer Token (Encrypted):", "module.jose.outerToken");
        map.put("Generate Nested JWT", "module.jose.generateNested");
        map.put("Decrypt & Verify Nested JWT", "module.jose.verifyNested");
        map.put("Token (Input/Output):", "module.jose.tokenIo");
        map.put("Inner Payload (Output):", "module.jose.innerPayload");
        map.put("JSON Web Algorithms (JWA)", "module.jose.jwaTitle");
        map.put("Supported Algorithms Registry", "module.jose.registry");
        map.put("Type", "module.jose.type");
        map.put("Description", "module.jose.description");
        map.put("Unified Token Inspector", "module.jose.inspector");
        map.put("Paste any JOSE token (JWS or JWE) to see a visual breakdown of its components.", "module.jose.inspectorHelp");
        map.put("Analyze Token", "module.jose.analyze");
        map.put("Expand Report", "module.jose.expandReport");
        map.put("Copy Report", "module.jose.copyReport");
        map.put("Visual Breakdown:", "module.jose.visualBreakdown");
        return map;
    }

    public static Map<String, String> payments() {
        Map<String, String> map = common();
        map.put("💳 CVV Operations (CVV/CVV2/iCVV)", "module.payments.cvvTitle");
        map.put("Type:", "module.payments.type");
        map.put("CVK A (Hex):", "module.payments.cvkA");
        map.put("CVK B (Hex):", "module.payments.cvkB");
        map.put("PAN:", "module.payments.pan");
        map.put("Expiry (YYMM):", "module.payments.expiry");
        map.put("Service Code:", "module.payments.serviceCode");
        map.put("ATC/Tracker:", "module.payments.atc");
        map.put("Generate CVV", "module.payments.generateCvv");
        map.put("Verify CVV", "module.payments.verifyCvv");
        map.put("Result will appear here...", "module.payments.resultPrompt");
        map.put("🔢 Clear PIN Blocks", "module.payments.clearPinTitle");
        map.put("Encode PIN Block", "module.payments.encodePinBlock");
        map.put("PIN (4-12 digits):", "module.payments.pinDigits");
        map.put("Format:", "module.payments.format");
        map.put("Decode PIN Block", "module.payments.decodePinBlock");
        map.put("PIN Block (Hex):", "module.payments.pinBlockHex");
        map.put("🔐 Encrypted PIN Blocks (ISO)", "module.payments.encryptedPinTitle");
        map.put("Encode", "module.payments.encode");
        map.put("PIN:", "module.payments.pin");
        map.put("Encryption Key (Hex):", "module.payments.encryptionKey");
        map.put("Decode", "module.payments.decode");
        map.put("Encrypted PIN Block (Hex):", "module.payments.encryptedPinBlock");
        map.put("Decryption Key (Hex):", "module.payments.decryptionKey");
        map.put("🔑 PIN Generation (IBM 3624)", "module.payments.ibmTitle");
        map.put("Generate PIN from Offset", "module.payments.generatePinOffset");
        map.put("PVK (Hex):", "module.payments.pvk");
        map.put("Conversion Table:", "module.payments.conversionTable");
        map.put("Offset (4-16 digits):", "module.payments.offset");
        map.put("Validation Data Config", "module.payments.validationConfig");
        map.put("Start Pos:", "module.payments.startPos");
        map.put("Length:", "module.payments.length");
        map.put("Pad Char:", "module.payments.padChar");
        map.put("Generate PIN", "module.payments.generatePin");
        map.put("Verify PIN", "module.payments.verifyPin");
        map.put("PIN to Verify:", "module.payments.pinToVerify");
        map.put("🔑 PIN Utilities (Offset & PVV)", "module.payments.utilitiesTitle");
        map.put("Generate Offset (IBM 3624)", "module.payments.generateOffset");
        map.put("Dec Table (16 digits):", "module.payments.decTable");
        map.put("Desired PIN:", "module.payments.desiredPin");
        map.put("Generate Offset", "module.payments.generateOffsetButton");
        map.put("Generate PVV (VISA)", "module.payments.generatePvv");
        map.put("PIN:", "module.payments.pin");
        map.put("PVK Index:", "module.payments.pvkIndex");
        map.put("Generate PVV", "module.payments.generatePvvButton");
        map.put("Derive PIN from PVV (VISA)", "module.payments.derivePvv");
        map.put("Target PVV:", "module.payments.targetPvv");
        map.put("Find PIN", "module.payments.findPin");
        map.put("🔐 DUKPT KSN, TDES & AES", "module.payments.dukptTitle");
        map.put("BDK (hex):", "module.payments.bdk");
        map.put("KSN (hex):", "module.payments.ksn");
        map.put("TDES key purpose:", "module.payments.tdesPurpose");
        map.put("AES key usage:", "module.payments.aesUsage");
        map.put("Inspect KSN / Derive Key", "module.payments.inspectDerive");
        map.put("AES DUKPT PIN block (ISO 9564-4, 16 bytes; lab):", "module.payments.aesPinBlockHelp");
        map.put("Process AES PIN block", "module.payments.processAesPin");
        return map;
    }

    public static Map<String, String> emv() {
        Map<String, String> map = common();
        map.put("🔬 EMV TLV Inspector", "module.emv.tlvTitle");
        map.put("BER-TLV hexadecimal:", "module.emv.tlvInput");
        map.put("Inspect EMV TLV", "module.emv.inspectTlv");
        map.put("CDOL/DDOL Builder", "module.emv.dolBuilder");
        map.put("Build DOL Data", "module.emv.buildDol");
        map.put("🔑 Session Key Derivation", "module.emv.sessionTitle");
        map.put("Derive ICC Master Key (Action A)", "module.emv.deriveIcc");
        map.put("IMK (Hex):", "module.emv.imk");
        map.put("PAN Seq:", "module.emv.panSeq");
        map.put("Derive Session Key (SK)", "module.emv.deriveSession");
        map.put("ATC (Hex):", "module.emv.atc");
        map.put("Derive Keys", "module.emv.deriveKeys");
        map.put("💳 ARQC Generation", "module.emv.arqcTitle");
        map.put("Session Key (Hex):", "module.emv.sessionKey");
        map.put("Terminal Data (Raw - Overrides fields below):", "module.emv.rawTerminal");
        map.put("Transaction Data (Individual Fields):", "module.emv.transactionFields");
        map.put("Amount:", "module.emv.amount");
        map.put("Amount Other:", "module.emv.amountOther");
        map.put("Currency:", "module.emv.currency");
        map.put("Country:", "module.emv.country");
        map.put("ATC (Info):", "module.emv.atcInfo");
        map.put("TVR:", "module.emv.tvr");
        map.put("Date (YYMMDD):", "module.emv.date");
        map.put("Type:", "module.emv.type");
        map.put("UN:", "module.emv.un");
        map.put("ICC Data:", "module.emv.iccData");
        map.put("Padding:", "module.emv.padding");
        map.put("Generate ARQC", "module.emv.generateArqc");
        map.put("🔄 ARQC Validation & ARPC", "module.emv.arpcTitle");
        map.put("ARQC (from card):", "module.emv.arqc");
        map.put("Response Code (ARC):", "module.emv.arc");
        map.put("CSU (Optional):", "module.emv.csu");
        map.put("Prop. Auth. Data (Opt):", "module.emv.propAuth");
        map.put("Method:", "module.emv.method");
        map.put("Generate ARPC", "module.emv.generateArpc");
        map.put("Verify ARQC (Sim)", "module.emv.verifyArqc");
        map.put("🎞 Track 2 Data", "module.emv.trackTitle");
        map.put("Discretionary Data:", "module.emv.discretionary");
        map.put("Encode Track 2", "module.emv.encodeTrack");
        map.put("Track 2 Hex / String:", "module.emv.trackInput");
        map.put("Decode Track 2", "module.emv.decodeTrack");
        return map;
    }

    public static Map<String, String> openPgp() {
        Map<String, String> map = common();
        map.put("OpenPGP / GPG Laboratory", "module.pgp.title");
        map.put("Check GnuPG…", "module.pgp.checkGpg");
        map.put("Run GnuPG Interop…", "module.pgp.runInterop");
        map.put("Optional external GnuPG not checked", "module.pgp.gpgNotChecked");
        map.put("Key Generation", "module.pgp.keyGeneration");
        map.put("Generate RSA Key Pair", "module.pgp.generateRsa");
        map.put("Public key (ASCII armor)", "module.pgp.publicArmor");
        map.put("Secret key (laboratory only)", "module.pgp.secretKey");
        map.put("Operations (Text / Armor)", "module.pgp.operations");
        map.put("Load input…", "module.pgp.loadInput");
        map.put("Text/ASCII armor only; 16 MiB limit", "module.pgp.inputHelp");
        map.put("Encrypt", "module.pgp.encrypt");
        map.put("Decrypt", "module.pgp.decrypt");
        map.put("Sign Detached", "module.pgp.signDetached");
        map.put("Sign Attached", "module.pgp.signAttached");
        map.put("Clear-sign", "module.pgp.clearSign");
        map.put("Verify Detached", "module.pgp.verifyDetached");
        map.put("Verify Attached", "module.pgp.verifyAttached");
        map.put("Verify Clear-sign", "module.pgp.verifyClearSign");
        map.put("Verify with GnuPG", "module.pgp.verifyGpg");
        map.put("Clear data", "module.pgp.clearData");
        map.put("Binary File Operations (max. 16 MiB)", "module.pgp.fileOperations");
        map.put("Encrypt File…", "module.pgp.encryptFile");
        map.put("Decrypt File…", "module.pgp.decryptFile");
        map.put("Sign File…", "module.pgp.signFile");
        map.put("Verify File…", "module.pgp.verifyFile");
        map.put("Detached signature (ASCII armor)", "module.pgp.detachedArmor");
        map.put("Load signature…", "module.pgp.loadSignature");
        map.put("Save signature…", "module.pgp.saveSignature");
        map.put("Inspect signature", "module.pgp.inspectSignature");
        map.put("Output / Result", "module.pgp.output");
        map.put("Save output…", "module.pgp.saveOutput");
        return map;
    }

    public static Map<String, String> pades() {
        Map<String, String> map = common();
        map.put("PDF Advanced Electronic Signatures (PAdES)", "module.pades.title");
        map.put("PAdES laboratory — local PKCS#12 signing key", "module.pades.help");
        map.put("Signs PDF incrementally as Baseline-B, or Baseline-T when timestamping is explicitly enabled. It never overwrites an output file. 64 MiB limit.", "module.pades.warning");
        map.put("Input PDF:", "module.pades.input");
        map.put("Choose PDF…", "module.pades.choosePdf");
        map.put("Output PDF:", "module.pades.output");
        map.put("Choose output…", "module.pades.chooseOutput");
        map.put("Signing Key Source:", "module.pades.keySource");
        map.put("Local PKCS#12", "module.pades.localKey");
        map.put("PKCS#11 Token", "module.pades.token");
        map.put("Choose key…", "module.pades.chooseKey");
        map.put("Load Token Keys", "module.pades.loadKeys");
        map.put("Add RFC 3161 signature timestamp (PAdES-T)", "module.pades.addTimestamp");
        map.put("Add visible signature text", "module.pades.visibleText");
        map.put("Page", "module.pades.page");
        map.put("Width", "module.pades.width");
        map.put("Height", "module.pades.height");
        map.put("(PDF points; lower-left origin)", "module.pades.coordinatesHelp");
        map.put("Signed with CryptoCarver laboratory", "module.pades.visibleDefault");
        map.put("Validation Configuration (local truststore/CRL only)", "module.pades.validationConfig");
        map.put("Truststore:", "module.pades.truststore");
        map.put("Choose...", "module.pades.choose");
        map.put("CRL Evidence:", "module.pades.crlEvidence");
        map.put("Sign PDF", "module.pades.sign");
        map.put("Inspect Signatures", "module.pades.inspect");
        map.put("Validate PDF", "module.pades.validate");
        map.put("Save DSS Reports…", "module.pades.saveReports");
        map.put("PAdES result will appear here...", "module.pades.resultPrompt");
        return map;
    }

    public static Map<String, String> asic() {
        Map<String, String> map = common();
        map.put("ASiC Containers", "module.asic.title");
        map.put("ASiC-S laboratory — one payload plus detached CAdES-BES signature", "module.asic.help");
        map.put("Creates a bounded ASiC-S ZIP container. Inspection checks the mimetype and detached signature; it does not establish certificate trust, revocation or LTV.", "module.asic.warning");
        map.put("Input File:", "module.asic.input");
        map.put("Choose input…", "module.asic.chooseInput");
        map.put("Output File:", "module.asic.output");
        map.put("Choose output…", "module.asic.chooseOutput");
        map.put("Signing Key Source:", "module.asic.keySource");
        map.put("Local PKCS#12", "module.asic.localKey");
        map.put("PKCS#11 Token", "module.asic.token");
        map.put("Choose key…", "module.asic.chooseKey");
        map.put("Load Token Keys", "module.asic.loadKeys");
        map.put("Create ASiC-S", "module.asic.createS");
        map.put("Inspect / Verify", "module.asic.inspect");
        map.put("Experimental ASiC-E / CAdES — multiple payloads plus a SHA-256 manifest", "module.asic.experimental");
        map.put("Choose payloads…", "module.asic.choosePayloads");
        map.put("Create ASiC-E", "module.asic.createE");
        map.put("Choose truststore…", "module.asic.chooseTruststore");
        map.put("ASiC result will appear here...", "module.asic.resultPrompt");
        return map;
    }
}
