package com.cryptocarver.utils;

import com.cryptocarver.model.HistoryCommand;
import com.cryptocarver.model.OperationDetail;
import com.cryptocarver.model.SecretVisibilityProfile;
import java.util.List;

/** Produces a human-readable history report without weakening secret visibility. */
public final class HistoryReportExporter {
    private HistoryReportExporter() { }

    public static String toMarkdown(HistoryCommand item, SecretVisibilityProfile visibility) {
        if (item == null) throw new IllegalArgumentException("History item is required");
        SecretVisibilityProfile policy = visibility == null ? SecretVisibilityProfile.REDACTED : visibility;
        StringBuilder report = new StringBuilder("# CryptoCarver operation report\n\n");
        report.append("- **Operation:** ").append(escapeInline(item.getOperation())).append('\n');
        report.append("- **Recorded:** ").append(escapeInline(item.getTimestamp())).append('\n');
        report.append("- **Secret visibility:** ").append(policy).append("\n\n");
        report.append("## Details\n\n");

        List<OperationDetail> details = item.getStructuredDetails();
        if (details == null || details.isEmpty()) {
            return report.append("No structured details are available for this legacy history entry.\n").toString();
        }
        report.append("| Property | Class | Format | Value |\n|---|---|---|---|\n");
        for (OperationDetail detail : details) {
            if (detail == null || isOmitted(detail, policy)) continue;
            report.append('|').append(escapeInline(detail.name())).append('|')
                    .append(detail.classification()).append('|')
                    .append(escapeInline(detail.format())).append('|')
                    .append(escapeInline(visibleValue(detail, policy))).append("|\n");
        }
        return report.append("\n> Generated by CryptoCarver. Review this report before sharing it.\n").toString();
    }

    private static boolean isOmitted(OperationDetail detail, SecretVisibilityProfile visibility) {
        return detail.classification() == OperationDetail.Classification.SECRET
                && visibility == SecretVisibilityProfile.REDACTED;
    }

    private static String visibleValue(OperationDetail detail, SecretVisibilityProfile visibility) {
        if (detail.classification() == OperationDetail.Classification.SECRET && visibility == SecretVisibilityProfile.MASKED) return "***MASKED***";
        if (detail.classification() == OperationDetail.Classification.SENSITIVE && visibility != SecretVisibilityProfile.FULL_LAB) return "***MASKED***";
        return detail.value() == null ? "" : detail.value();
    }

    private static String escapeInline(String value) {
        return (value == null ? "" : value).replace("\\", "\\\\").replace("|", "\\|")
                .replace("\r\n", "<br>").replace("\n", "<br>").replace("\r", "<br>");
    }
}
