package com.cryptocarver.crypto;

import com.cryptocarver.crypto.ThalesKeyBlockOperations.Unwrapped;
import com.cryptocarver.crypto.ThalesKeyBlockOperations.VersionId;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The Thales Key Block cryptography, against a block generated by EFTLab's
 * BP-Tools Cryptographic Calculator 21.06 on 19 September 2026.
 *
 * <p>The payShield manual describes the algorithms but not how their keys come
 * from the LMK, and leaves the authenticator's scope ambiguous. Both were
 * settled by asking the vendor's own tool to wrap a key under the 3DES Key
 * Block test LMK that clause 8.8.1 publishes, and reading back the derived
 * KBEK and KBAK it prints alongside the result.</p>
 *
 * <p>Every value below is from that run. Nothing here is a round trip against
 * itself, which is the point: the Thales <em>variant</em> scheme in
 * {@link ThalesLmkOperations} taught this branch that encrypt and decrypt agree
 * with each other even when both are wrong.</p>
 */
class ThalesKeyBlockCryptoTest {

    /** payShield manual, clause 8.8.1: the 3DES Key Block test LMK. */
    private static final String KBPK = "0123456789ABCDEF8080808080808080FEDCBA9876543210";

    private static final String PLAIN_KEY = "735B3125EFF2E04ABFBFA1670180A168";
    private static final String HEADER = "00072B0TN00E0002";
    private static final String ENCRYPTED_KEY = "56A37F894FD49E61DD3FA27FDE8919D07F7AA966F8BF39AB";
    private static final String MAC = "31D00034";
    private static final String KEY_BLOCK = HEADER + ENCRYPTED_KEY + MAC;

    /** The six bytes of random padding that run used, recovered from the block. */
    private static final String PADDING = "E370F35CCB09";

    /** The two variants the tool printed for that KBPK. */
    private static final String KBEK = "44660022CCEE88AAC5C5C5C5C5C5C5C5BB99FFDD33117755";
    private static final String KBAK = "4C6E082AC4E680A2CDCDCDCDCDCDCDCDB391F7D53B197F5D";

    // =====================================================================
    // The two things the manual does not say
    // =====================================================================

    @Test
    void theKeysAreVariantsOfTheLmkWithTheX9143Constants() {
        // KBEK = KBPK XOR 45..45 and KBAK = KBPK XOR 4D..4D, across the whole
        // key. 'E' for encryption, 'M' for MAC — the variant method of ANSI
        // X9.143 versions A and C, which the manual never names.
        assertEquals(KBEK, ThalesKeyBlockOperations.encryptionKey(KBPK));
        assertEquals(KBAK, ThalesKeyBlockOperations.authenticationKey(KBPK));
    }

    @Test
    void theAuthenticatorCoversTheEncryptedKeyDataAndNotTheClear() {
        // Clause 8.7 says "the Key Data" for 3DES where it says "the clear key
        // block" for AES. That asymmetry is real. Over the clear data the MAC
        // comes out C033654B; the hardware says 31D00034.
        Unwrapped unwrapped = ThalesKeyBlockOperations.unwrap(KBPK, KEY_BLOCK);

        assertTrue(unwrapped.authentic(), ThalesKeyBlockOperations.describe(unwrapped));
        assertEquals(MAC, unwrapped.expectedAuthenticator());
        assertNotEquals("C033654B", unwrapped.expectedAuthenticator(),
                "C033654B is what covering the clear key data would give");
    }

    // =====================================================================
    // The vector, both ways
    // =====================================================================

    @Test
    void theToolsBlockUnwrapsToTheKeyItWasGiven() {
        Unwrapped unwrapped = ThalesKeyBlockOperations.unwrap(KBPK, KEY_BLOCK);

        assertEquals(PLAIN_KEY, unwrapped.clearKey());
        assertEquals(128, unwrapped.keyBits());
        assertEquals(PADDING, unwrapped.padding());
        assertTrue(unwrapped.authentic());
    }

    @Test
    void wrappingTheSameInputsReproducesTheToolsBlockExactly() {
        // The padding is random in normal use, so it is supplied here. With it
        // fixed, the output has to be the vendor tool's own output, character
        // for character.
        String block = ThalesKeyBlockOperations.wrap(KBPK, HEADER, PLAIN_KEY, PADDING);

        assertEquals(KEY_BLOCK, block);
        assertEquals(ENCRYPTED_KEY, block.substring(16, 64));
        assertEquals(MAC, block.substring(64));
    }

    @Test
    void theSchemeTagIsAcceptedInFrontOfTheBlock() {
        assertEquals(PLAIN_KEY, ThalesKeyBlockOperations.unwrap(KBPK, "S" + KEY_BLOCK).clearKey());
    }

    @Test
    void theBlockTheToolProducedIsWellFormedByItsOwnRules() {
        // Usage B0 with algorithm T and mode N: permitted by clause 8.5.1.2.
        assertTrue(ThalesKeyBlockOperations.parse(KEY_BLOCK).wellFormed());
        assertEquals("Base Derivation Key (BDK-1)", ThalesKeyBlockOperations.keyUsage("B0").description());
    }

    // =====================================================================
    // What must not pass
    // =====================================================================

    @Test
    void changingOnlyAParityBitOfTheLmkChangesNothing() {
        // Worth pinning, because it is the obvious way to write the test below
        // and it does not work. The low bit of every DES key byte is a parity
        // bit that the cipher ignores, so 'FE...10' and 'FE...11' are the same
        // key and the block still authenticates.
        String parityTwin = "0123456789ABCDEF8080808080808080FEDCBA9876543211";

        Unwrapped unwrapped = ThalesKeyBlockOperations.unwrap(parityTwin, KEY_BLOCK);

        assertTrue(unwrapped.authentic());
        assertEquals(PLAIN_KEY, unwrapped.clearKey());
    }

    @Test
    void theWrongLmkIsCaughtByTheAuthenticator() {
        // 01 -> 03 differs in bit 1, which DES does not ignore.
        String otherKbpk = "0323456789ABCDEF8080808080808080FEDCBA9876543210";

        assertThrows(IllegalArgumentException.class,
                () -> ThalesKeyBlockOperations.unwrap(otherKbpk, KEY_BLOCK),
                "the wrong LMK must not quietly produce a key");
    }

    @Test
    void alteringTheLastCipherBlockFailsTheAuthenticatorCleanly() {
        // The length field lives in the first plaintext block, so tampering
        // with the last ciphertext block leaves it readable and the failure
        // shows up exactly where it should: the authenticator.
        String tampered = HEADER + ENCRYPTED_KEY.substring(0, 46) + "00" + MAC;

        Unwrapped unwrapped = ThalesKeyBlockOperations.unwrap(KBPK, tampered);

        assertFalse(unwrapped.authentic());
        assertNotEquals(PADDING, unwrapped.padding());
        assertTrue(ThalesKeyBlockOperations.describe(unwrapped).contains("Do not trust the key"));
    }

    @Test
    void alteringTheFirstCipherBlockIsRefusedOutright() {
        // Here the length field itself is destroyed, so there is nothing to
        // report; the message has to lead with the authenticator rather than
        // with the nonsense length that follows from it.
        String tampered = HEADER + "57" + ENCRYPTED_KEY.substring(2) + MAC;

        IllegalArgumentException thrown = assertThrows(IllegalArgumentException.class,
                () -> ThalesKeyBlockOperations.unwrap(KBPK, tampered));
        assertTrue(thrown.getMessage().startsWith("The authenticator does not match"),
                thrown.getMessage());
    }

    @Test
    void alteringTheHeaderFailsTheAuthenticatorToo() {
        // This is the whole point of a key block: the header is bound to the
        // key. Turning "no special restrictions" into "encrypt only" must not
        // be something anyone can do with a text editor.
        String tampered = "00072B0TE00E0002" + ENCRYPTED_KEY + MAC;

        assertFalse(ThalesKeyBlockOperations.unwrap(KBPK, tampered).authentic());
    }

    /**
     * The AES scheme was refused by name here until a vector for it was
     * captured; it now has one and lives in {@link ThalesKeyBlockAesTest}. What
     * survives of that refusal is this: the two versions are different
     * constructions, and a 3DES block's key data is not a whole number of AES
     * blocks, so reading one as the other fails on the arithmetic rather than
     * producing a wrong key quietly.
     */
    @Test
    void aThreeDesBlockReadAsAnAesOneFailsOnItsLength() {
        String mislabelled = "10072B0AN00E0002" + ENCRYPTED_KEY + MAC + "12345678";

        IllegalArgumentException thrown = assertThrows(IllegalArgumentException.class,
                () -> ThalesKeyBlockOperations.unwrap(KBPK, mislabelled));
        assertTrue(thrown.getMessage().contains("16-byte block cipher"), thrown.getMessage());
    }

    @Test
    void theAesSchemePadsToSixteenBytesRatherThanEight() {
        IllegalArgumentException thrown = assertThrows(IllegalArgumentException.class,
                () -> ThalesKeyBlockOperations.wrap(KBPK, "10072B0AN00E0002", PLAIN_KEY, PADDING));
        assertTrue(thrown.getMessage().contains("exactly 14 bytes of padding"), thrown.getMessage());
    }

    @Test
    void paddingOfTheWrongLengthIsRefusedWithTheNumberNeeded() {
        IllegalArgumentException thrown = assertThrows(IllegalArgumentException.class,
                () -> ThalesKeyBlockOperations.wrap(KBPK, HEADER, PLAIN_KEY, "0011"));
        assertTrue(thrown.getMessage().contains("exactly 6 bytes of padding"), thrown.getMessage());
    }

    @Test
    void randomPaddingStillRoundTrips() {
        String block = ThalesKeyBlockOperations.wrap(KBPK, HEADER, PLAIN_KEY, null);
        Unwrapped unwrapped = ThalesKeyBlockOperations.unwrap(KBPK, block);

        assertEquals(PLAIN_KEY, unwrapped.clearKey());
        assertTrue(unwrapped.authentic());
        assertNotEquals(PADDING, unwrapped.padding(), "the padding should not be the fixed one");
    }

    @Test
    void aDoubleLengthKeyBlockLmkIsAlsoAccepted() {
        // Clause 8.8 calls a Key Block LMK triple-length, but the variant is
        // over the whole key either way, so a 16-byte one works and is worth
        // allowing on a bench.
        String shortKbpk = "0123456789ABCDEF8080808080808080";
        String block = ThalesKeyBlockOperations.wrap(shortKbpk, HEADER, PLAIN_KEY, PADDING);

        assertEquals(PLAIN_KEY, ThalesKeyBlockOperations.unwrap(shortKbpk, block).clearKey());
        assertNotEquals(KEY_BLOCK, block, "a different LMK must give a different block");
    }

    @Test
    void theVersionEnumStillKnowsBothKinds() {
        assertEquals('0', VersionId.DES.tag());
        assertEquals('1', VersionId.AES.tag());
    }
}
